import { NextRequest } from "next/server";
import { db } from "@/db";
import { datasets, images, annotations, classes, evaluations, models, experiments, datasetSplits } from "@/db/schema";
import { eq, sql } from "drizzle-orm";
import { writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import path from "path";
import { resolveDatasetIdentifier } from "@/lib/dataset";

import { REPORTS_DIR } from "@/lib/paths";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { type, datasetId, modelId } = body;

    if (!type) {
      return Response.json({ error: "Report type required" }, { status: 400 });
    }

    let reportContent = "";
    let reportFilename = "";

    if (type === "dataset_card") {
      if (!datasetId) {
        return Response.json({ error: "datasetId required for dataset card" }, { status: 400 });
      }

      const dsRecord = await resolveDatasetIdentifier(datasetId);
      if (!dsRecord) {
        return Response.json({ error: "Dataset not found" }, { status: 404 });
      }

      const dataset = await db.select().from(datasets).where(eq(datasets.id, dsRecord.id)).limit(1);
      if (dataset.length === 0) {
        return Response.json({ error: "Dataset not found" }, { status: 404 });
      }

      const ds = dataset[0];
      const totalImages = await db.select({ count: sql<number>`count(*)::int` }).from(images).where(eq(images.datasetId, dsRecord.id));
      const totalAnnotations = await db.select({ count: sql<number>`count(*)::int` }).from(annotations).where(eq(annotations.datasetId, dsRecord.id));
      const classList = await db.select().from(classes).where(eq(classes.datasetId, dsRecord.id));

      reportContent = `# Dataset Card: ${ds.name}\n\n`;
      reportContent += `**Dataset ID:** ${ds.datasetId}\n`;
      reportContent += `**Theme:** ${ds.theme || "N/A"}\n`;
      reportContent += `**Description:** ${ds.description || "N/A"}\n`;
      reportContent += `**Location:** ${ds.collectionLocation || "N/A"}\n`;
      reportContent += `**Photographer:** ${ds.photographer || "N/A"}\n`;
      reportContent += `**Device:** ${ds.device || "N/A"}\n`;
      reportContent += `**Lighting:** ${ds.lightingCondition || "N/A"}\n`;
      reportContent += `**Status:** ${ds.status}\n`;
      reportContent += `**Version:** ${ds.version}\n\n`;
      reportContent += `## Statistics\n\n`;
      reportContent += `- **Total Images:** ${totalImages[0].count}\n`;
      reportContent += `- **Total Annotations:** ${totalAnnotations[0].count}\n`;
      reportContent += `- **Number of Classes:** ${classList.length}\n\n`;
      reportContent += `## Classes\n\n`;
      reportContent += `| Class | Index | Color |\n|---|---|---|\n`;
      for (const cls of classList) {
        reportContent += `| ${cls.name} | ${cls.classIndex} | ${cls.color || "N/A"} |\n`;
      }
      reportContent += `\n## Collection Methodology\n\n`;
      reportContent += `Traditional Indian Lamps & Ritual Objects collected with ${ds.device || "standard camera"} at ${ds.collectionLocation || "various locations"}.\n`;
      reportContent += `\n*Generated by VisionBharat — DataGenesis 2026*\n`;

      reportFilename = `dataset_card_${ds.datasetId}_${Date.now()}.md`;
    } else if (type === "model_card") {
      if (!modelId) {
        return Response.json({ error: "modelId required for model card" }, { status: 400 });
      }

      const model = await db.select().from(models).where(eq(models.id, modelId)).limit(1);
      if (model.length === 0) {
        return Response.json({ error: "Model not found" }, { status: 404 });
      }

      const m = model[0];
      reportContent = `# Model Card: ${m.name}\n\n`;
      reportContent += `**Model ID:** ${m.modelId}\n`;
      reportContent += `**Architecture:** ${m.architecture || "Custom VisionBharatDetector"}\n`;
      reportContent += `**Version:** ${m.version}\n`;
      reportContent += `**Input Size:** ${m.imageSize}x${m.imageSize}\n`;
      reportContent += `**Number of Classes:** ${m.numClasses}\n`;
      reportContent += `**Parameter Count:** ${m.parameterCount || "N/A"}\n`;
      reportContent += `**From Scratch:** ${m.isFromScratch ? "YES" : "NO"}\n`;
      reportContent += `**Uses Pretrained:** ${m.usesPretrained ? "YES (NOT ALLOWED)" : "NO"}\n\n`;
      reportContent += `## Performance\n\n`;
      reportContent += `- **Precision:** ${m.precision ?? "NOT EVALUATED"}\n`;
      reportContent += `- **Recall:** ${m.recall ?? "NOT EVALUATED"}\n`;
      reportContent += `- **F1:** ${m.f1 ?? "NOT EVALUATED"}\n`;
      reportContent += `- **IoU:** ${m.iou ?? "NOT EVALUATED"}\n`;
      reportContent += `- **mAP:** ${m.mapScore ?? "NOT EVALUATED"}\n\n`;
      reportContent += `## Limitations\n\n`;
      reportContent += `- Model is trained from scratch with limited dataset\n`;
      reportContent += `- Performance improves with more training data\n`;
      reportContent += `- CPU inference is slower than GPU\n\n`;
      reportContent += `*Generated by VisionBharat — DataGenesis 2026*\n`;

      reportFilename = `model_card_${m.modelId}_${Date.now()}.md`;
    } else if (type === "research_report") {
      reportContent = `# VisionBharat Research Report\n\n`;
      reportContent += `## Methodology\n\n`;
      reportContent += `India-centric dataset engineering and from-scratch computer vision platform.\n\n`;
      reportContent += `## Competition Compliance\n\n`;
      reportContent += `- Model initialized randomly (Kaiming/Normal init)\n`;
      reportContent += `- No pretrained weights used\n`;
      reportContent += `- No external training datasets\n`;
      reportContent += `- All metrics computed from actual data\n\n`;
      reportContent += `*Generated by VisionBharat — DataGenesis 2026*\n`;
      reportFilename = `research_report_${Date.now()}.md`;
    } else {
      return Response.json({ error: "Unknown report type" }, { status: 400 });
    }

    if (!existsSync(REPORTS_DIR)) {
      await mkdir(REPORTS_DIR, { recursive: true });
    }

    const filePath = path.join(REPORTS_DIR, reportFilename);
    await writeFile(filePath, reportContent, "utf-8");

    return Response.json({
      report: {
        type,
        filename: reportFilename,
        path: filePath,
        content: reportContent,
      },
    }, { status: 201 });
  } catch (error) {
    console.error("[REPORTS] Error:", error);
    return Response.json({ error: "Report generation failed" }, { status: 500 });
  }
}

export async function GET() {
  try {
    if (!existsSync(REPORTS_DIR)) {
      return Response.json({ reports: [], total: 0 });
    }

    const { readdirSync, statSync } = await import("fs");
    const files = readdirSync(REPORTS_DIR).filter(f => f.endsWith(".md"));
    const reports = files.map(f => ({
      filename: f,
      path: path.join(REPORTS_DIR, f),
      size: statSync(path.join(REPORTS_DIR, f)).size,
      modified: statSync(path.join(REPORTS_DIR, f)).mtime,
    }));

    return Response.json({ reports, total: reports.length });
  } catch (error) {
    console.error("[REPORTS] GET Error:", error);
    return Response.json({ error: "Failed to list reports" }, { status: 500 });
  }
}
